### ISSUE TITLE
Dockerize application

### ISSUE THREAD

**Issue by murat** [murat/stories#4]

**Comment by rfussien** [comment]
I wouldn't recommend to include docker config into a project as it is not a project responsibility to take over infrastructure.
Instead, you might just recommend to use something like [laradock](https://laradock.io/) or [larakube](https://github.com/markhilton/larakube) in your readme file.

**Comment by alicankustemur** [comment]
I can take this one but you need help me this project arch.

**Comment by murat** [comment]
@rfussien thank you for recommendations. I pleasured. @alicankustemur this is a story sharing platform (only a toy project), Remi is right, it does not need to be dockerized, but if you want to take this I'm going to be glad.

**Comment by kmjayadeep** [comment]
Is it still open?

**Comment by murat** [comment]
No thanks.
